apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: db:3306
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_HOME
          value: https://ucsf-app.cloud.okteto.net
        - name: WORDPRESS_SITE
          value: https://ucsf-app.cloud.okteto.net
        image: ucsfapp/site:latest
        imagePullPolicy: ""
        name: wordpress
        ports:
        - name: wordpress-port
          containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: wordpress-data
        persistentVolumeClaim:
          claimName: wordpress-data
status: {}
